runtime: python311

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

# Use larger instance for better performance
instance_class: F4  # ← Changed from F2 (2GB RAM instead of 1GB)

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

env_variables:
  OPENAI_API_KEY: "Need to be put in manually while running" ##################################################################################################################################################
  CHROMADB_GCS_BUCKET: "aurelia-rag-data"
  DATABASE_URL: "sqlite:////tmp/concept_notes.db"
  SIMILARITY_THRESHOLD: "0.45"
  TOP_K_RESULTS: "5"
  MAX_CONTEXT_TOKENS: "6000"
  LLM_MODEL: "gpt-4o-mini"
  EMBEDDING_MODEL: "text-embedding-3-large"
  EMBEDDING_DIMENSIONS: "3072"
  CHROMADB_COLLECTION_NAME: "fintbx"
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"

handlers:
  - url: /.*
    script: auto
    secure: always

# CRITICAL: Extended timeouts for ChromaDB loading
readiness_check:
  path: "/health"
  check_interval_sec: 60  # ← Increased from 30
  timeout_sec: 30  # ← Increased from 10
  failure_threshold: 5  # ← Increased from 3
  success_threshold: 1
  app_start_timeout_sec: 600  # ← ADDED: 10 minute startup timeout

liveness_check:
  path: "/health"
  check_interval_sec: 300
  timeout_sec: 30  # ← Increased from 10
  failure_threshold: 5  # ← Increased from 3
  success_threshold: 1